// This file is auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          display_name: string
          avatar_emoji: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          display_name?: string
          avatar_emoji?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          display_name?: string
          avatar_emoji?: string
          created_at?: string
          updated_at?: string
        }
      }
      rooms: {
        Row: {
          id: string
          name: string
          slug: string
          owner_id: string | null
          estimation_values: string[]
          estimations_visible: boolean
          active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          owner_id?: string | null
          estimation_values?: string[]
          estimations_visible?: boolean
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          owner_id?: string | null
          estimation_values?: string[]
          estimations_visible?: boolean
          active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      room_participants: {
        Row: {
          id: string
          room_id: string
          user_id: string
          is_admin: boolean
          joined_at: string
          last_seen_at: string
        }
        Insert: {
          id?: string
          room_id: string
          user_id: string
          is_admin?: boolean
          joined_at?: string
          last_seen_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          user_id?: string
          is_admin?: boolean
          joined_at?: string
          last_seen_at?: string
        }
      }
      estimations: {
        Row: {
          id: string
          room_id: string
          user_id: string
          value: string | null
          submitted_at: string
        }
        Insert: {
          id?: string
          room_id: string
          user_id: string
          value?: string | null
          submitted_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          user_id?: string
          value?: string | null
          submitted_at?: string
        }
      }
    }
    Views: {
      room_state: {
        Row: {
          room_id: string
          room_name: string
          room_slug: string
          estimation_values: string[]
          estimations_visible: boolean
          participants: Json
        }
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
